### PR TITLE
Remove abuse of AggressiveInlining/AggressiveOptimization

### PR DESCRIPTION
**Pull request by john-h-k**
Remove the double bounds checks and lets underlying field do checking.

Remove abuse of attribute, given `AggressiveOptimization` does NOT make code faster and is only used in very specific scenarios not applicable here. Methods are small and forcing inlinging here is pointless

### CODE REVIEW

**Comment by budgetdevv** [comment]
Hey! First of all...thanks for taking your time to contribute. As I'm relatively new to "low-level" stuff ( And C# in general ), I would like to enquire about a thing or two.

First of all, to address the double bound checks - The goal here was to elide those checks; its actually inspired by List<T> 's implementation ( Which I **may** have accidentally screwed up )

As for the inlining, I've written similar code before...and inlining seem to improve benchmark results. But then again, I'm no authority when it comes to benchmarks 😅 

Could you enlighten me regarding the above points?

**Comment by john-h-k** [comment]
> First of all, to address the double bound checks - The goal here was to elide those checks; its actually inspired by List 's implementation ( Which I may have accidentally screwed up )

Yes, but you are eliding the check... by doing the check. `if (Index > arr.Length)` IS a bounds check. By adding it, you might remove the native bounds check, but overall you still have one bounds check. List has to do a bounds check because the size of a list is less than that of the underlying array

> As for the inlining, I've written similar code before...and inlining seem to improve benchmark results. But then again, I'm no authority when it comes to benchmarks 😅

Firstly, let's get `AggressiveOptimization` out of the way. The rule of thumb is simply never use it, it is badly named and complex and not what you want.

Secondly, `AggressiveInlining`. Inlining can make code faster, but in 99% of scenarios, the JIT can work out exactly when to inline and when not to. `AggressiveInlining` is a hint by the dev that they know more about the method than the JIT does, and so although the JIT thinks it is a bad idea to inline it, it may still well do so.

Inlining is not always a win. It can bloat code and actually make it significantly slower. Think about it, if `AggressiveInlining` on everything made it always faster, wouldn't the JIT do it by default?

All of your methods are small enough that the JIT will inline them by itself in most scenarios, so the attribute means nothing

**Comment by KoziLord** [comment]
> Hey! First of all...thanks for taking your time to contribute. As I'm relatively new to "low-level" stuff ( And C# in general ), I would like to enquire about a thing or two.
> 
> First of all, to address the double bound checks - The goal here was to elide those checks; its actually inspired by List 's implementation ( Which I **may** have accidentally screwed up )
> 
> As for the inlining, I've written similar code before...and inlining seem to improve benchmark results. But then again, I'm no authority when it comes to benchmarks 😅
> 
> Could you enlighten me regarding the above points?

The general idea is that since the code is so small, the JIT would inline it anyway, as for `AggressiveOptimization` what that does is force the JIT to compile the method immediately in the highest JIT tier that's supposed to produce the highest quality code, the issue with that is however that the JIT would compile that anyway if it mattered (got hit enough times) AND it makes some optimisations impossible unless it re-JITs (which afaik it doesn't).
`readonly static` is one of the optimisations that can actually not happen if you use `AggressiveOptimization` for example.

**Comment by budgetdevv** [comment]
> Yes, but you are eliding the check... by doing the check. if (Index > arr.Length)

From what I understand...I'd have to do bound-checking anyway, since a Resize is needed should the underlying array be filled ( This is an expected case )

> Inlining is not always a win. It can bloat code and actually make it significantly slower. Think about it, if AggressiveInlining on everything made it always faster, wouldn't the JIT do it by default?

Actually, I had a lot of people warn me about inlining, and I gave it a deep thought too in fact! So I came to the conclusion that I'd let benchmarks determine if I should inline certain methods. Not sure if such is the right approach though...

> The general idea is that since the code is so small, the JIT would inline it anyway, as for AggressiveOptimization what that does is force the JIT to compile the method immediately in the highest JIT tier that's supposed to produce the highest quality code, the issue with that is however that the JIT would compile that anyway if it mattered (got hit enough times) AND it makes some optimisations impossible unless it re-JITs (which afaik it doesn't).
readonly static is one of the optimisations that can actually not happen if you use AggressiveOptimization for example.

Yup, I'm aware of such ( Thanks to lurking in the #lowlevel channel 😅 )...so I avoid them on stuff that uses static readonly(s)

**Comment by john-h-k** [comment]
> From what I understand...I'd have to do bound-checking anyway, since a Resize is needed should the underlying array be filled ( This is an expected case )

Well, from your current impl, you don't, you simply did a comparison to array length - I removed that, which just improves inlining candidacy (removes explicit throw), reduces IL size, and is functionally identical or better, given this is for an indexer not an `Add` method.

> Actually, I had a lot of people warn me about inlining, and I gave it a deep thought too in fact! So I came to the conclusion that I'd let benchmarks determine if I should inline certain methods. Not sure if such is the right approach though...

Benchmarks in isolation are never a good test for inlining. In isolation, a method is *always* quicker when inlined. The best approach is to let the JIT do its thing - all these will almost certainly be inlined anyway

> Yup, I'm aware of such ( Thanks to lurking in the #lowlevel channel 😅 )...so I avoid them on stuff that uses static readonly(s)

Even outside of static readonly(s), there are dragons with this attribute. Note that 99% of high perf code does not use them. Immediate full JIT worsens startup time, can cause lag, and have a lower quality of optimisations

**Comment by budgetdevv** [comment]
> Well, from your current impl, you don't, you simply did a comparison to array length - I removed that, which just improves inlining candidacy (removes explicit throw), reduces IL size, and is functionally identical or better, given this is for an indexer not an Add method.

Ah yes, I think I mixed it up with Add()...looks good 👍🏻

**Comment by budgetdevv** [comment]
Pardon me for being annoying, but all of my projects ( So far ) are basically made for learning / experimental purposes. As such, I'd love to know the reasoning behind the remaining two changes.

First of all, I do not understand the removal of `RuntimeHelpers.IsReferenceOrContainsReferences<T>()` ; an explanation would be nice.

Will be addressing the issue of `Unsafe.SkipInit()` in the pull request dedicated to it

**Comment by john-h-k** [comment]
It's a JIT constant. Using it inline is clearer and makes the JITs job optimizing it easier

**Comment by budgetdevv** [comment]
Ok, sounds good thanks

**Comment by budgetdevv** [comment]
🥳

**Pull request merged**
